services:
  app:
    image: 'dangin:v1'
    build: .
    container_name: 'dangin'
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - DISPLAY=${DISPLAY}
    volumes:
      - ./:/danbots/dangin
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: 'nvidia'
              capabilities: ['gpu']
              count: 'all'
    ipc: 'host'
    ulimits:
      memlock: '-1'
      stack: '67108864'
    tty: true
  
